### ISSUE TITLE
Source tarball is missing CHANGELOG.md, so installation from source fails

### ISSUE THREAD

**Issue by andersk** [jaysonsantos/python-binary-memcached#251]
`pip install --no-binary=python-binary-memcached python-binary-memcached` fails with:

`ModuleNotFoundError: No module named 'm2r'`

If I `pip install m2r` and try again, it still fails with:

`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-qjpxb4mq/python-binary-memcached_747c4c032a4842959449fa809cd93e16/CHANGELOG.md'`

Full output:

```console
$ pip install --no-binary=python-binary-memcached python-binary-memcached
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Collecting python-binary-memcached
  Using cached python-binary-memcached-0.31.1.tar.gz (95 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-fh9a5v38/python-binary-memcached_48c4237f0aa044eb815b878829f7d75f/setup.py", line 5, in <module>
          from m2r import convert
      ModuleNotFoundError: No module named 'm2r'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

$ pip install m2r
Collecting m2r
  Using cached m2r-0.3.1-py3-none-any.whl
Collecting docutils
  Using cached docutils-0.19-py3-none-any.whl (570 kB)
Collecting mistune<2
  Using cached mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Installing collected packages: mistune, docutils, m2r
Successfully installed docutils-0.19 m2r-0.3.1 mistune-0.8.4

$ pip install --no-binary=python-binary-memcached python-binary-memcached
Collecting python-binary-memcached
  Using cached python-binary-memcached-0.31.1.tar.gz (95 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qjpxb4mq/python-binary-memcached_747c4c032a4842959449fa809cd93e16/setup.py", line 23, in <module>
          read("README.rst"), convert(read("CHANGELOG.md"))
        File "/tmp/pip-install-qjpxb4mq/python-binary-memcached_747c4c032a4842959449fa809cd93e16/setup.py", line 9, in read
          return open(os.path.join(os.path.dirname(__file__), filename)).read()
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-qjpxb4mq/python-binary-memcached_747c4c032a4842959449fa809cd93e16/CHANGELOG.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by jaysonsantos** [comment]
fixed and released https://pypi.org/project/python-binary-memcached/0.31.2/
