### ISSUE TITLE
TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by duzhuoyizui** [jaysonsantos/python-binary-memcached#49]
`client.set('aa', 'bb')` raised 

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    client.set('aa', 'bb')
  File "/usr/local/lib/python3.4/dist-packages/bmemcached/client.py", line 161, in set
    returns.append(server.set(key, value, time))
  File "/usr/local/lib/python3.4/dist-packages/bmemcached/protocol.py", line 506, in set
    return self._set_add_replace('set', key, value, time)
  File "/usr/local/lib/python3.4/dist-packages/bmemcached/protocol.py", line 477, in _set_add_replace
    time, str_to_bytes(key), value))
  File "/usr/local/lib/python3.4/dist-packages/bmemcached/protocol.py", line 221, in _send
    self._open_connection()
  File "/usr/local/lib/python3.4/dist-packages/bmemcached/protocol.py", line 133, in _open_connection
    self._send_authentication()
  File "/usr/local/lib/python3.4/dist-packages/bmemcached/protocol.py", line 272, in _send_authentication
    if 'PLAIN' not in methods:
TypeError: 'str' does not support the buffer interface
```

**Comment by jaysonsantos** [comment]
@duzhuoyizui Sorry for the delay. Did you have authentication enabled on your server?

**Comment by duzhuoyizui** [comment]
I had removed to Redis.
