### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by slowbackspace** [jaysonsantos/python-binary-memcached#59]
```
import bmemcached
client = bmemcached.Client(('192.168.2.139:11211', '192.168.2.140:11211'), 'username', 'password')
print (client.stats())
```

```
Traceback (most recent call last):
  File "sandbox.py", line 4, in <module>
    print (client.stats())
  File "/home/ubuntu/telegraf/service_agent/venv_ubuntu/lib/python3.5/site-packages/bmemcached/client.py", line 325, in stats
    returns[server.server] = server.stats(key)
  File "/home/ubuntu/telegraf/service_agent/venv_ubuntu/lib/python3.5/site-packages/bmemcached/protocol.py", line 820, in stats
    self._send(packed)
  File "/home/ubuntu/telegraf/service_agent/venv_ubuntu/lib/python3.5/site-packages/bmemcached/protocol.py", line 221, in _send
    self._open_connection()
  File "/home/ubuntu/telegraf/service_agent/venv_ubuntu/lib/python3.5/site-packages/bmemcached/protocol.py", line 133, in _open_connection
    self._send_authentication()
  File "/home/ubuntu/telegraf/service_agent/venv_ubuntu/lib/python3.5/site-packages/bmemcached/protocol.py", line 272, in _send_authentication
    if 'PLAIN' not in methods:
TypeError: a bytes-like object is required, not 'str'
```

I also tried [bmemcached-cli](https://github.com/RedisLabs/bmemcached-cli) just to be sure. It works fine with the same username and password.

**Comment by slowbackspace** [comment]
Oh, it's fixed by https://github.com/jaysonsantos/python-binary-memcached/commit/fc96c53079f89f471a24fcfabe08b4940b3e05db
Someone should update package on PyPI.
https://pypi.python.org/pypi/python-binary-memcached

**Comment by jaysonsantos** [comment]
Hi @slowbackspace I am going to do it now. Thank!
